[workspace]
resolver = "2"
members = ["waker", "waker-cli", "waker-server"]

[workspace.package]
edition = "2021"
authors = ["DarkCeptor44"]
homepage = "https://github.com/DarkCeptor44/waker"
repository = "https://github.com/DarkCeptor44/waker"

[workspace.dependencies]
anyhow = "^1"
